### PR TITLE
Silence "Messaging unqualfied id" warnings

### PR DESCRIPTION
**Pull request by ksuther**
More unqualified id warning fixes that popped up in Xcode 10.

### CODE REVIEW

**Review by ElektrojungeAtWork — APPROVED** [review]
Hi Kent,

thanks for this. You're awesome (as always). <3 

Ben

PS: Unfortunately, I can't provide an ETA for when this will be released officially.

**Comment by ElektrojungeAtWork** [comment]
Fixes #490

**Review by guperrot — APPROVED** [review]

**Comment by elektrojunge** [comment]
@ksuther we resolved our CI issues, would you please update your branch with the latest from develop? I’m happy to create a new PR based on your change but wanted to give you the opportunity to update yours. 🙏

**Comment by elektrojunge** [comment]
🙏

**Pull request merged**
