### PR TITLE
Feature/emailauthtransparent

### PR DESCRIPTION
**Pull request by alkinney**
This reuses the email authentication logic but adds the functionality to have the application provide the email and provide a transparent (no UI presented) login process.

### CODE REVIEW

**Comment by alkinney** [comment]
This commit does have some changes that merit discussion.

1. Pulling the appSecretError into a separate method
2. Copying the methods outright is not ideal seeing as the
viewcontroller passed in is never used but maybe there's a reason they are there? I can make a new commit to refactor these.
3. Tests are pending discussion.

**Comment by lumaxis** [comment]
Hey @alkinney,

sorry for the long radio silence on this. We're discussing your proposed changes internally and if and how we will support your proposed feature in the future.
We'll get back to once we know more. :relaxed:

**Comment by alkinney** [comment]
Awesome thanks! Sorry for the delayed response this must have slipped through the cracks!


Just a heads up what we're also changing:


- Enabling updates in the AppStore for internal employees

- Reading the timestamp instead of the CFBundleVersion because we would prefer not to change our versioning system


Though I don't plan on submitting a pull request for either of these.


Also no decision currently made yet for this feature?


Thanks!

-Alex


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by lumaxis** [comment]
@alkinney We had several discussions about your PR in the last couple of weeks and decided that we are generally interested in enhancing the abilities our authentication module provides but would to like to add this in a more general, modular, and reusable way. This will most likely be in the fashion of the customizable alertViewHandler API that we added for our CrashManager.
This unfortunately means that we can't accept your Pull Request at this time as we feel it would add a constrained workaround for a very specific use case which is not what we are looking for right now.

Please let me say though that we highly appreciate your effort and the idea it brought to us! (No, seriously. This might sound like a text module but we've seriously been thinking hard about this!) We're looking forward to more of your contributions in the future :relaxed:
Also, we won't start work on this immediately, so if you have time and motivation to change this PR in the way so it fits our ideas, we'll be happy to accept it!

**Comment by TroubleMakerBen** [comment]
We're closing this as we won't continue to work on this.

Sorry for the long silence on this.

🖖

**Pull request closed without merging**
