### PR TITLE
Fix NSURLSession memory leak in Swift apps

### PR DESCRIPTION
**Pull request by anlinde**
This should fix the issue raised in https://github.com/bitstadium/HockeySDK-iOS/issues/237

Tested the changes before the patch with Instruments and also after the patch which prooved the leaks going away.

### CODE REVIEW

**Comment by MMasterson** [comment]
How can I export this as a .framework?

**Comment by MMasterson** [comment]
leak fixed! +1 thank you!

**Comment by lumaxis** [comment]
Thanks for the help @anlinde! :relaxed: We will probably do some refactoring in the near future for a better longterm solution but this is a good fix for now :+1:

**Comment by johnryan** [comment]
I'm still seeing leaks in the latest version, is this a new issue?

screen shot 2016-06-14 at 4 52 50 pm

**Comment by FranzBusch** [comment]
Same here still getting leaks

**Comment by lumaxis** [comment]
Thanks everyone. This is already fixed in the current `develop` branch and also the latest ]beta release](https://github.com/bitstadium/HockeySDK-iOS/releases/tag/4.1.0-beta.2) by https://github.com/bitstadium/HockeySDK-iOS/commit/5a5eaf018b77f35200cc6ed6636c01a4b3c76ac7

**Pull request merged**
