### PR TITLE
Improve logging to be more customizable and versatile

### PR DESCRIPTION
**Pull request by lumaxis**
This is not meant to be merged yet, just a very first suggestion on the general approach and open to discussion!

@TroubleMakerBen @ranterle @anlinde @chrwend FYI 🙂

- [x] Add documentation, especially how to set a custom log handler

### CODE REVIEW

**Comment by 0xced** [comment]
Great to see you liked my post. 😃

The implementation looks good but is missing a crucial part: a way to hook into the logging function. Currently the logs always end up being emitted with NSLog in the `logLevel:function:line:message:` method. Adding a log handler would allow apps to direct logs wherever they want.

This is better than the previous version as hooking would be easy with swizzling but it would be even better with a first class log hanlder. 😉

**Comment by lumaxis** [comment]
@0xced Yep, I'm aware :grin: Was not sure if we actually want to have that functionality right now but it's definitely still on my mind.

**Comment by chrwend** [comment]
@lumaxis, can you update the docs to have more information about this feature?

**Comment by chrwend** [comment]
Looks good to me, tested with NSLogger and CocoaLumberjack. The generated docs look a little bit weird though. Feel free to merge

**Comment by lumaxis** [comment]
@chrwend I thought I already did this in https://github.com/bitstadium/HockeySDK-iOS/pull/244/commits/94b3c684d08a4bdcec417fa0cc007249a13bdf27 ?

**Comment by chrwend** [comment]
@lumaxis Awesome!

**Comment by 0xced** [comment]
Glad to see
```objc
+ (void)setLogHandler:(BITLogHandler)logHandler;
```
🎉

**Pull request merged**
