### PR TITLE
[WIP] Podspec divided in subspecs.

### PR DESCRIPTION
**Pull request by dtorres**
I've divided the podspec in subspecs, one for each feature.

I still need to make another change to ensure the resources are only added if a subspec requires them so please don't merge yet.

**IMPORTANT:** For this to work I had to default to every feature be turned off.

### CODE REVIEW

**Comment by anlinde** [comment]
Thanks for that!

We are planning to move the standard CocoaSpec to use the binary distribution, since too many people are either messing up their projects so that builds fail or are using new Xcode (Beta) versions with new warnings introduced and expect them to be "fixed" (even though those are not highlighting any mailfunctions in the SDK) right away.

I am not sure if your system can be integrated with that approach as an option. Any thoughts?

**Comment by dtorres** [comment]
It can't be integrated as is with a static library. 

The idea behind this approach is that no unnecessary code/classes are compiled and only the necessary resources are added.

There is nothing we can do against people messing with their projects (even with a static library you can make a mess) so I believe there is not enough benefit of going that way here. What it can be done though is suppress all warnings in the target generated by cocoapods, that way you won't get complaints for "useless" warnings.

**Comment by anlinde** [comment]
The problem with source distribution is: people compile things with non-tested environments which cause a lot of effort on our side and it is harder for beginners to find their issues. Distributing a binary is always well tested, safe and easier to integrate.

The main idea now would be this:

1. Default CocoaPods setup uses binary distribution
2. Optionally compile from source and define which modules should be included

Not sure if we need two cocoapod specs for that or if everything can be included into one spec.

**Comment by dtorres** [comment]
Yes it can be done.
Say we create a subspec called staticlib which just includes the binary file, all public headers and all resources, then just by defining staticlib as the default subspec you get what you described.

And then, people can use HockeySDK/All (which should be renamed to compiledlib or something) or HockeyApp/[component] if they choose.

**Comment by dtorres** [comment]
I've changed the name of the default podspec to CompiledLib, once the static lib is ready, it will be just add a subspec for it and make it default for it to work as intended.

I've also changed the approach of feature config to use one only for cocoapods. This makes all test pass again.

The only thing missing is to add the graphic resources in the subspecs that use them. (I'm guessing all except for CrashReporting but I'll see that another time)

**Comment by anlinde** [comment]
I'll close this pull request since I continued on top of your work and made it work also with binary subspecs, see https://github.com/bitstadium/HockeySDK-iOS/pull/169

Thanks again!

**Pull request closed without merging**
