### PR TITLE
Fixes carthage build for Xcode 10.2

### PR DESCRIPTION
**Pull request by werner77**
Removes all custom architecture configuration (ARCHS, VALID_ARCHS)

### CODE REVIEW

**Comment by ettore** [comment]
What's the reason for not reviewing this very useful PR? I'm confused. Any official explanations would be very much appreciated.

**Comment by gbejarano01** [comment]
Any progress on this?

**Comment by pyrou** [comment]
Maybe @ElektrojungeAtWork ?

**Comment by MatkovIvan** [comment]
@gbejarano01 @pyrou @werner77 See https://github.com/bitstadium/HockeySDK-iOS/issues/548#issuecomment-493181473

**Pull request closed without merging**
