### PR TITLE
if available, give info-collecting textFields a content type

### PR DESCRIPTION
**Pull request by diederich**
The idea is to enable 'one-tap' filling of those textfields.
I haven't actually tested this, as I don't think I have HockeySDK included in source-form anywhere right now, and the demo app doesn't seem to show the feedback UI.
Do you have a Demo app that does?

### CODE REVIEW

**Comment by diederich** [comment]
This seems to work, although it could use some "massaging". E.g. update the "Save" indicator state after a paste of the email / name.
I also saw that other parts in the file have `__IPHONE_OS_VERSION_MAX_ALLOWED` guards. Is building against < iOS 10 SDK still supported?

**Comment by ElektrojungeAtWork** [comment]
Hey Peter von Frosta, ;)

yes, we support iOS 9 and up.... we'll be in touch about the PR.

As always, thanks for the contribution =)

**Comment by diederich** [comment]
Hey @elektrojunge - hope things are good in Seattle! 👋 🤗  

I'll add the `__IPHONE_OS_VERSION_MAX_ALLOWED` for compiling against an < iOS 10 SDK

**Comment by diederich** [comment]
🎁 😄

**Review by ElektrojungeAtWork — COMMENTED** [review]
Thanks for this! =)

As @elamalani said in another issue here on GitHub, we can't provide an ETA as to when the next release will happen because we are busy making [App Center](https://github.com/Microsoft/AppCenter-SDK-Apple) awesome.

**Review by ElektrojungeAtWork — APPROVED** [review]

**Pull request merged**
