### PR TITLE
Fix typos and spelling errors

### PR DESCRIPTION
**Pull request by tewha**
Various spelling problems and typos.

I left alone words that were correct in one variation of English or another, like "customisation" or "-our" words.

There were a few that were part of internationalization or API. I didn't touch those.

### CODE REVIEW

**Comment by tewha** [comment]
I have a few more incoming, sorry. :)

**Comment by tewha** [comment]
There. That should do it. See also #139.

**Comment by TheRealKerni** [comment]
Hey Steven, thanks a LOT for this!

**Comment by tewha** [comment]
You're welcome! I have an eye for this sort of thing, so I figured it was my good deed for the day. :)

**Pull request merged**
