### PR TITLE
Force New Feedback thread

### PR DESCRIPTION
**Pull request by tabuchid**
Adds a configuration to allow for a new thread to be generated for each feedback item.
This is useful in scenarios where feedback is used more for bug reporting and feature requests then as a user communication tool.

### CODE REVIEW

**Comment by jorgesilva** [comment]
@tabuchid is there a way to achieve this without modifying the SDK? I achieved something similar on Android using the SDK's public methods and I want to know if this is possible on iOS as well so I can incorporate it into my work without breaking compatibility with the SDK (if the pull request is not accepted)

**Comment by tabuchid** [comment]
@jorgesilva I haven't found a way to do this w/o modifying the SDK. One of my colleagues added the feature to Android as well https://github.com/bitstadium/HockeySDK-Android/pull/189
From my understanding the HockeyTeam hasn't merged this because it hasn't been implemented on all platforms but with Android and iOS being done that only leaves Xamarin so if you know any Xamarin engineers that could pick it up we potentially can get this merged.

**Comment by tivadartimea** [comment]
Hi @tabuchid, I'm working with @jorgesilva. I worked before with Xamarin, could you tell me what should I do? Maybe I can help.

**Comment by ranterle** [comment]
Hi @tabuchid, thanks for the PR. We're looking at this and will be discussing this internally.

**Comment by tabuchid** [comment]
@tivadartimea Sorry for the late reply. The changes are pretty straightforward. This PR and https://github.com/bitstadium/HockeySDK-Android/pull/189 add a flag called `forceNewThread` which just ensure the feedback thread token is nil when feedback is sent. This causes hockey to generate a new thread for that piece of feedback.
It'd be awesome if you can get this to work for Xamarin cause then we'll have it implemented in all three environments which is what I was told was one of the blockers for merging this.

**Comment by TroubleMakerBen** [comment]
Hey guys,

We've scheduled a release within the first half of december which will include this.

**Comment by tabuchid** [comment]
@TroubleMakerBen 🎉! Thank you!

**Comment by jorgesilva** [comment]
🤗

**Pull request merged**
