### PR TITLE
Update BITHockeyHelper.m

### PR DESCRIPTION
**Pull request by mtoon**
Added additional characters to escape

### CODE REVIEW

**Comment by lumaxis** [comment]
@mtoon I'll refactor the whole URL construction in `BITUpdateManager.m` a bit in #251 but I'm still happy to merge this as it's used in many other places. Could you please also update the unit test for this method with a matching case? Thanks! :blush:

**Comment by mtoon** [comment]
@lumaxis Just pushed that..  Looks like the CI build is going.  Thanks again!

**Comment by lumaxis** [comment]
@mtoon Sorry to bother again but would you mind rebasing your branch onto the upstream `develop` and then force-pushing it so we can get rid of that ugly merge commit? 🙂

**Comment by lumaxis** [comment]
Thanks :+1:

**Pull request merged**
